version: '3.8'
services:
  mariadb:
    image: lexabernal/db_microtech:arm64
    environment:
      - MARIADB_ROOT_PASSWORD=my-password
      - MARIADB_DATABASE=my-database
      - MARIADB_USER=my-user
      - MARIADB_PASSWORD=my-user-password
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3307:3306"
  billsender:
    image: lexabernal/bill_sender:arm64
    environment:
      - name=value
    ports:
    - "3308:3000"

volumes:
  mariadb-data: